## jsonbl
## Coursera: Programing in R
## Week 3 Programming Assignment 2
## Caching the inverse of a matrix

## This function takes a special "matrix" object that can cache its inverse.
## Input requrest a square, invertible matrix as per assignment
## example matrix data can be created by:
## x <- matrix(sample(25),nrow=5,ncol=5)

## Function can be used to:
## 1. set the value of a matrix (set)
## 2. get the value of a matrix (get)
## 3. set a value to indicate that the matrix is already inverted (setinv)
## 4. get the value that indicates whether the matrix is inverted (getinv)

makeCacheMatrix <- function(x = matrix()) {
  inv <- NULL
  set <- function(y) {
    x <<- y
    inv <<- NULL
  }
  get <- function() x
  setinv <- function(inverse="inverse") inv <<- inverse
  getinv <- function() inv
  list(set=set, get=get, setinv=setinv, getinv=getinv)
  }

## This function reads the special matrix generated by the makeCacheMatrix function
## If the inverse flag is null, then the inverse matrix is calculated and the flag is changed
## If the inverse flag is not null, then the cached inverted matrix is retrievied.
## Input for the function should be a list generated by the makeCacheMatrix
## example input file can be generated by running:
## m <- makeCacheMatrix(x)
## example usage would be:
## cacheSolve(m) OR cacheSolve(makeCacheMatrix(x))

cacheSolve <- function(x) {
  inv <- x$getinv()
  if (!is.null(inv)){
    message("getting cached data...")
    inv
    }
  m <- x$get()
  x_inv <- solve(m)
  x$setinv("inverse")
  return(x_inv)
}
